### ISSUE TITLE
installation doesn't work in HASS

### ISSUE THREAD

**Issue by mik55** [oischinger/eufyp2pstream#10]
Hello Hans,
thank you very much for this project. I hope it solves my problem with the live video of the Eufy Doorbell E340. 
However, I cannot install it in my Home Assistant installation. 
I copied the unpacked zip file into the "/usr/share/hassio/addons" folder and tried the installation using the "install the addon" link. Unfortunately I get the message “Addon not found”. Here is the link that is called: "http://192.168.x.x:8123/_my_redirect/supervisor_addon?addon=local_eufyp2pstream".
The requirements for “Eufy Security WS” addon and “go2RTC” addon are met.
I notice that you write in the readme: "Copy this directory to /addons/eufyp2pstream", really an absolute path in the root directory? But if I copy the directory here, the installation doesn't work either.
By the way, absolute paths "/data/options.json" and "python3 -u /eufyp2pstream.py $EUFY_WS_PORT" are entered in the file eufyp2pstream/files/. Is that right?

Many regards
Michael

Hallo Hans,
vielen Dank für dieses Projekt. Ich hoffe es löst meine Problem mit dem Live-Video der Eufy Doorbell E340. 
Allerdings kann ich es in meiner Home Assistant Installation nicht installieren. 
Ich habe das ausgepackte Zip File in den Ordner "/usr/share/hassio/addons" kopiert und die Installation über den Link "install the addon" probiert. Leider kommt dann die Meldung "Addon nicht gefunden". Hier der Link der aufgerufen wird: "http://192.168.x.x:8123/_my_redirect/supervisor_addon?addon=local_eufyp2pstream".
Die Voraussetzungen "Eufy Security WS" Addon und "go2RTC" Addon sind erfüllt.
Mir fällt aus, dass Du im Readme schreibst: "Copy this directory to /addons/eufyp2pstream", wirklich ein absoluter Pfad im Root-Directory? Aber wenn ich das Verzeichnis hierhin kopiere klappt die Installation auch nicht.
Übrigens, im File eufyp2pstream/files/ sind absolute Pfade "/data/options.json" und "python3 -u /eufyp2pstream.py $EUFY_WS_PORT" eingetragen. Ist das richtig?

**Comment by oischinger** [comment]
The instructions on the readme are for Home Assistant OS. The addons are located under /addons

Once you press the "add addon button" in the addons page it should pop up in the list of local addons. You might have to check for updates before that.

**Comment by mik55** [comment]
Many thanks for your response. 
Unfortunately I can't find a way to install your addon from a local source. Do you have an idea?
