### ISSUE TITLE
Error Eufyp2pstream in HassOS 

### ISSUE THREAD

**Issue by mik55** [oischinger/eufyp2pstream#11]
Hello Hans, 
After you answered me that your tool "eufyp2pstream only runs in HassOS, I installed HassOS in my test environment. Unfortunately, the installation of your tool does not work here either. I get a response window with the content: Add-on could not be installed / The command 'bin/sh -c pip install aiohttp asyncio' returned a non-zero code: 1. 
It is not possible to install aiohttp as the root user using a command; the system responds with the help file for the “pip” command. Can you help me here?
Thanks
Michael
Hallo Hans, 
nachdem Du mir geantwortet hast, dass dein Tool "eufyp2pstream nur in hassos läuft, habe ich in meiner Testumgebung hassos installiert. Leider klappt auch hier die Installation deines Tools nicht. Ich bekomme ein Antwortfenster mit dem Inhalt: Add-on konnte nicht installiert werden / The command 'bin/sh -c pip install aiohttp asyncio' returned a non-zero code: 1. 
Eine Installation von aiohttp als User root per Kommando ist nicht möglich, das System antwortet mit der Hilfedate des Befehls "pip". Kannst Du mir hier helfen?
Danke
Michael

**Comment by oischinger** [comment]
That's weits.
Please provide the logs of the Home Assistant Supervisor when building the addon.

It contains the full output of what went wrong.

By the way: you cannot pip install directly when sshing to Home Assistant OS. The pip command needs to be run within the docker Container of the addon. Usually this is being taken care of in the Dockerfile. But for some reason the pip command fails. W/o logs I can only speculate. It could be missing Network connectivity or some python Version issue.

**Comment by mik55** [comment]
Hello Hans,
you find the Logfiles in Attachement.
many thanks for the help
Michael
[supervisor_2024-05-28T09-50-22.875Z.log](https://github.com/oischinger/eufyp2pstream/files/15467349/supervisor_2024-05-28T09-50-22.875Z.log)
[home-assistant_2024-05-28T09-46-15.427Z.log](https://github.com/oischinger/eufyp2pstream/files/15467350/home-assistant_2024-05-28T09-46-15.427Z.log)
P.S. I see the gcc tool is missing. -;((

**Comment by oischinger** [comment]
@mik55 Please check out the latest commit. it should fix your issue

**Comment by mik55** [comment]
Hello Hans,
that's work. The installation is OK.
Many thanks for your work.
Michael
