### ISSUE TITLE
How is this different then RTSP Simple Server?

### ISSUE THREAD

**Issue by cms365** [oischinger/eufyp2pstream#7]
An honest question as I’m very intrigued by this project… how does this materially differ from the RTSP Simple Server included in the Eufy Security integration?

I’ve been struggling getting my Eufy doorbell working with HA or Frigate and curious how your solution may differ. 

Thanks!

**Comment by oischinger** [comment]
RTSP Simple Server allows you to create an RTSP stream from Eufy's P2P stream when using the [Eufy Security custom component](https://github.com/fuatakgun/eufy_security). Newer versions of that custom component also work w/o RTSP simple server and just use go2RTC to create the RTSP or WebRTC stream. This is exactly what also this addon does.

Only difference being: This addon does not require you to start/stop streaming via some Home Assistant automations.
Instead the addon notices when a stream is opened on demand (e.g. when you show a webrtc card in lovelace) and then starts streaming automatically. Once all the clients are gone (e.g. the browser which showed the lovelace card is closed) it stops the stream. Thus it does not unnecessarily consume CPU resources

**Comment by cms365** [comment]
This is exactly what I was hoping you’d say! Starting streams on the P2P cams has been painful. Nice stuff Hans! Will be trying it out shorty. Thank you for the reply.

**Comment by oischinger** [comment]
Please let me know how good it works with long-time streaming and Frigate. I tested only with short-time streams which I show on the Dashboard for a few seconds.
There might be timeout/auto-disconnect issues for longer streams.

**Comment by cms365** [comment]
Hey @oischinger!

Sorry for the delay. Finally got a chance to give this a go. Install went perfectly!

It seems this add-on won't quite work with my setup. I need to look at it a bit closer, but the issue is likely because I have 4 Eufy cameras connected to the Eufy Security add-on. 3 are native RTSP cams that are pumping into go2rtc and then Frigate. The p2p camera is a doorbell 2k. It seems when I add a config to go2rtc for the doorbell, it breaks Frigate and go2rtc. I need to spend some more time looking at it, as it is possible I missed something. Appreciate your work on this and understand it's early in development. Just wanted to share my experience.

**Comment by oischinger** [comment]
In your case the addon might pickup thr wrong camera. As of writing the code is super-dumb and just picks up the last (!) of your devices no matter if it has P2P or not.
See also my comment here on how this behavior could be modified

**Comment by mercuryin** [comment]
I have a s100 eufy and using the eufy security addon alone or using it alongside your addon the p2p stream crash after like between 20 minutes to 1 hour. If you restart the eufy addon it works again. Do you have any idea how to solve it ? The eufy security addon developer looks like is not longer updating or answering issues, I just come across to your addon because is convenient to auto start the p2p session but if the eufy addon crash I can´t have a reliable stream to use with Frigate. Any ideas would be highly appreciated. Thanks !
